#!/bin/bash -e

PI_TARGET=aarch64-unknown-linux-gnu # alternative platforms: armv7-unknown-linux-gnueabihf

# check for dependencies
crs=$(cargo install --list | grep  cross | wc -l)
if (( crs == 0 ))
then
  echo "[INFO] Installing cross"
  cargo install -f cross
else
  echo "[INFO] Skipping 'Cross' installation as dependency already met"
fi

# PI build
cross build --release --target $PI_TARGET
